### ISSUE TITLE
"Remove" option doesn't remove dependency

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/antler-proj#21]
Content of the project.yaml file:
```yaml
#antler-proj::generated
#   This file was AUTOGENERATED.
#   Modification or removal of the above lines will cause antler-proj to deem the project as invalid.
#   Any changes made to this file will be lost when the tool updates this project.
#   generated with v1.0.0
#
# This file was auto-generated. Be aware antler-proj may discard added comments.


project: test_proj
version: 0.0.1
libraries:
  - name: test_app1
    lang: CXX
    compile_options: cmpl_opt;
    link_options: link_opt;
apps:
  - name: app
    lang: CXX
  - name: test_app
    lang: java
    compile_options: cpp_opt;
    link_options: link_pot;
  - name: test_app1
    lang: java
    compile_options: cpp_opt;
    link_options: link_pot;
    depends:
      - name: test_dep1
        from: 'https://github.com/larryk85/sample_contract'
        release: 0.0.1
        hash: hash
```

root@c1742fb0fdb3:/app# antler-proj remove /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test dep test_app1 test_dep1                                                             
Object: test_dep1 does not exist.

while removing of the test_app1 with it's dependency works well:

root@c1742fb0fdb3:/app# antler-proj remove /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test app test_app1          
Removing object: test_app1 from the project.

P.S. IMHO it would be better to write the message as "Object test_app1 has been removed" or something like this to make the user sure that the action has been completed successfully.
