### ISSUE TITLE
Incorrect processing of adding of dependency.

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/antler-proj#23]
As a user who doesn't know the antler-proj internals I would be confused of this error message:

root@c1742fb0fdb3:/app# antler-proj add /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test dep test_app test_dep "https://github.com/larryk85/sample_contract"           
[error_log] :: In this version of antler-proj only github shorthands are supported. Generalized git repos and archives will be supported in the next version.
[error_log] :: Error denpendency: test_dep is invalid.
[error_log] :: Dependency: test_dep is invalid.
[error_log] :: failed to add dependency

I want to add a dependency from github, I declared full path to the repository on github, I don't understand why it is wrong and why the program can't accept this repository. I mean that as a user I don't understand why "https://github.com/larryk85/sample_contract" is wrong but "larryk85/sample_contract" is OK.

After successful adding (according to the message) of the dependency I have following message:

root@c1742fb0fdb3:/app# antler-proj add /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test dep test_app test_dep "larryk85/sample_contract"
sh: 1: gh: not found
^^^^^^^^^^^^^^^^ As a user I don't understand what is this
[info_log] :: 
^^^^^^^^^ In looks like here should be some message but it was not printed because of bug
Object name (to update): test_app
Dependency name: test_dep
Dependency location: larryk85/sample_contract
tag/commit hash: 
release version: 
SHA256 hash: 

And actually the dependency was not added. The project file was not changed:

```yaml
project: test_proj
version: 0.0.1
apps:
  - name: test_app
    lang: CXX
    compile_options: ""
    link_options: ""
libs:
  - name: test_lib
    lang: CXX
    compile_options: compiler_opts
    link_options: linker_opts
```

After try to add dependency to the lib antler-proj returns the following error message:

root@c1742fb0fdb3:/app# antler-proj add /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test dep test_lib test_dep "larryk85/sample_contract" 0.0.1     
[error_log] :: Object test_lib does not exist in project.
[info_log] :: Wrote project manifest to /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test.
